name: HLint action
description: Checks that Haskell files are linted with HLint.
inputs:
  config:
    description: The HLint config to use.
    required: false
    default: .hlint.yaml
  pattern:
    description: The Haskell files to check.
    required: false
    default: '**/*.hs'
  version:
    description: The version of HLint to use.
    required: false
    default: latest
runs:
  using: node16
  main: main.js
branding:
  icon: trending-up
  color: purple
